import type { Metadata } from 'next'


export const metadata: Metadata = {
  title: 'auth',
  description: 'Generated by create next app',
}

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <div>auth</div>
      <body>{children}</body>
    </html>
  )
}
